# Generated by Django 4.0 on 2022-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchme', '0002_streamplatform_watch_list_delete_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_list',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
