# Generated by Django 4.0 on 2022-03-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchme', '0003_alter_watch_list_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_list',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchme.streamplatform'),
            preserve_default=False,
        ),
    ]
