# Generated by Django 4.0 on 2022-03-08 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('watchme', '0004_watch_list_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('desription', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(verbose_name=enum.auto)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='watchme.watch_list')),
            ],
        ),
    ]
