# Generated by Django 4.0 on 2022-03-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchme', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desription',
            new_name='description',
        ),
    ]
