# Generated by Django 4.0 on 2022-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchme', '0007_review_review_user_alter_review_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_list',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watch_list',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
